### PR TITLE
removing arch (and moving some models to be converted)

### PR DESCRIPTION
**Pull request by rdevon**
arch is old models used for research. The common ones are to moved to built-ins. Others are being moved to private repos

### CODE REVIEW

**Comment by rdevon** [comment]
Just removes `arch` from the repo

**Comment by ReyhaneAskari** [comment]
@rdevon are you planning to bring this code later to cortex or your other PR (https://github.com/rdevon/cortex2.0/pull/111/) have these?

**Comment by rdevon** [comment]
@ReyhaneAskari Most of the code actually is supposed to be private (part of current research) minus the models that I need to port over (which I moved to built-ins)

**Comment by ReyhaneAskari** [comment]
@rdevon , I see. But there are going to be in the history anyways. Are you ok with that?

**Review by ReyhaneAskari — APPROVED** [review]

**Comment by rdevon** [comment]
@ReyhaneAskari for now, yes. We can decide whether to make the hard decision of force-removing the history, but this needs to be done carefully.

**Comment by rdevon** [comment]
@joeljpoulin I agree. This might be best to do when we merge to master though because some of the history is mixed in there.

**Pull request merged**
