### PR TITLE
Refactored and redid backend

### PR DESCRIPTION
**Pull request by rdevon**
This PR has 0 flake8 errors.

Backend now uses aliases to handle keyword differences in routines and the model.

For example, a routine or build might reference a network "a_net", but this reference is only useful in the context of the routine or build. The model owns a dictionary of all the networks, and the routine simply has an alias (can be thought of a sort of pointer) to that network. That way, the routine can reference "a_net" without knowing how the model is using it.

Updated classifier, gan, vae, and ali to follow this framework.

Cleaned up code and fixed some small errors.

Cleaned up noise.py

Removed global network handler.

Now, routines and builds "own" their kwargs and help. These are containers of aliases which point to the model kwargs and help.

All models "train" correctly, but no tests are implemented. This is the next step.

cortex-config does not work (this script is not yet compatible with cortex.)

Note / TODO:
The interface for building models works, but it can be tricky to debug. This needs to be stressed tested as well as include more informative errors.

### CODE REVIEW

**Comment by rdevon** [comment]
Review away

**Comment by rdevon** [comment]
@ReyhaneAskari can we test travis integration on this PR?

**Comment by ReyhaneAskari** [comment]
@rdevon yes we should. @joeljpoulin should be working on this.

**Comment by joeljpoulin** [comment]
Test suites are too heavy to implement it all in 1 PR. A project card as been open to plan. Basic Flake8  has been run and corrected, ignoring E901 errors. The PR should be merge soon to avoid conflicts.

**Comment by rdevon** [comment]
@joeljpoulin 
https://travis-ci.com/rdevon/cortex2.0/builds/76582242

This is apparently because there is no "script" entry in .travis.yml. How to fix?

(from https://docs.travis-ci.com/user/languages/python/)

**Comment by ReyhaneAskari** [comment]
Why do we have so many CIs?

**Comment by joeljpoulin** [comment]
@rdevon 
> This is apparently because there is no "script" entry in .travis.yml. How to fix?
Attributing it as a `script` and not `before_script`.
Changes have been made to add tox in Travis-CI pipeline.

**Comment by joeljpoulin** [comment]
The build passed, but I'm not sure that it actually ran correctly the tox. I will change it to make it compatible only with Flake8 for now.

**Review by ReyhaneAskari — APPROVED** [review]
It's hard for me to follow what has happened specially because there is no test and there are many changes. I'm OK but you should be rebasing instead of merging when you want to bring the changes of another branch. With rebase you will not have the additional commit that appears in the PR which is basically empty.

**Pull request merged**
