### PR TITLE
Backend overhaul

### PR DESCRIPTION
**Pull request by rdevon**
In order to make cortex easier to use but less like a black box, various backend changes were made.

The user now has the option to change their build or routine functions, but also affect the main loop in various ways, adding needed flexibility without putting pressure on development to cover every use-case.

Notable methods are wrapped by cortex to take care of things better left to the backend, with things that people (hopefully) care about exposed to the user.

Several convenience functions were added to make it easier from the user standpoint to fetch data and pass arguments to functions.

Classifier, GAN, VAE, adversarial AE, ALI, and MINE are all implemented.

Finally, models can be trained using just `python <path to file> <arguments>` (see the classifier demo).

### CODE REVIEW

**Comment by rdevon** [comment]
@TiSU32 @Entodi @samLav What would be great is if you look at the models in built-ins and judge the PR based on how things are implemented. @IshmaelBelghazi If you could look at MINE that would be great.

**Comment by joeljpoulin** [comment]
Maybe the PR should be merged without waiting for the reviews if it's working locally on the author's computer. As the multiple changes are changing the behavior of the plugins, which is primordial for stress testing.

**Comment by joeljpoulin** [comment]
For
`cortex GAN --d.source CIFAR10 --d.copy_to_local
`
I get error 
```
Traceback (most recent call last):
  File "/u/poulijoe/.conda/envs/python3.6/bin/cortex", line 7, in <module>
    from cortex.main import main
ImportError: cannot import name 'main'
```

**Comment by joeljpoulin** [comment]
Simple experiment `cortex GAN --d.source CIFAR10 --d.copy_to_local ` returns `ImportError: cannot import name 'main'`.

**Review by Entodi — APPROVED** [review]
Currently reloading experiments and setting new experiments don't work.
`cortex -r ../cortex2.0/outs/test/binaries/test\(best_losses.classifier\).t7 ImageClassification`
Models can't be reloaded with this command
Because we don't have anymore `MODEL_HANDLER`, we need to rewrite for new framework `reload` and `setup_new` functions

In main training pipeline, I haven't found any issues.

I suggest approve PR of this branch to dev and to continue working on dev branch instead.

**Pull request merged**
