### PR TITLE
Implemented AE

### PR DESCRIPTION
**Pull request by lavoiems**
Basic implementation of an AE. Based the implementation on the classifier and gan implementation.

### CODE REVIEW

**Review by rdevon — COMMENTED** [review]
Looks good. It might be nice to add options such as noising etc at a later date. Did you test this?

**Comment by lavoiems** [comment]
I tested this on MNIST. I agree that adding a noising option could be a good idea. I will create an issue.

**Review by rdevon — APPROVED** [review]
AOK

**Comment by rdevon** [comment]
This one's a bit out of date.

**Pull request closed without merging**
